version: '3.8'

services:
  backend:
    image: asia-southeast2-docker.pkg.dev/your-gcp-project/backend-image:latest
    container_name: golang-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=34.128.100.213   # Gunakan IP Public Cloud SQL
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=saas_platform
    networks:
      - app-network

  frontend:
    image: asia-southeast2-docker.pkg.dev/your-gcp-project/frontend-image:latest
    container_name: landingpages
    restart: always
    ports:
      - "8081:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
