version: '3.8'

services:
  backend:
    build: ./golang-api
    container_name: golang-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=saas_platform
    networks:
      - app-network

  frontend:
    build: ./landingpages
    container_name: landingpages
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas_platform
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
