name: Deploy Backend to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker to use Google Artifact Registry
        run: |
          gcloud auth configure-docker asia-southeast2-docker.pkg.dev

      - name: Build & Push Docker Image to Google Artifact Registry
        run: |
          docker build -t asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/golang-api/backend:latest -f golang-api/Dockerfile .
          docker push asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/golang-api/backend:latest

      - name: Deploy Backend on Compute Engine
        run: |
          gcloud compute ssh ci-cd-saasbackend --zone=asia-southeast2-a --command "
          sudo docker pull asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/golang-api/backend:latest &&
          sudo docker stop backend || true &&
          sudo docker rm backend || true &&
          sudo docker run -d --name backend -p 8080:8080 --env-file /home/ubuntu/.env \
          asia-southeast2-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/golang-api/backend:latest
          "
