name: Deploy Frontend to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy-fe:
    name: Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Install Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Authenticate SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_INSTANCE_IP_FE }} >> ~/.ssh/known_hosts

      - name: Fix Permissions on Compute Engine
        run: |
          gcloud compute ssh ci-cd-saasfrontend --zone=asia-southeast2-a --command "
          sudo mkdir -p /var/www/html &&
          sudo chown -R \$USER:\$USER /var/www/html &&
          sudo chmod -R 755 /var/www/html"

      - name: Sync Frontend Files to Compute Engine
        run: |
          gcloud compute scp --recurse landingpages/* ci-cd-saasfrontend:/var/www/html --zone=asia-southeast2-a

      - name: Restart Nginx to Apply Changes
        run: |
          gcloud compute ssh ci-cd-saasfrontend --zone=asia-southeast2-a --command "
          sudo systemctl restart nginx"
